spring.application.name=algafood-api

server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/algafood?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.properties.hobernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create

#logging.level.org.hibernate.type=trace