spring.application.name=algafood-api

server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/algafood?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true
spring.jpa.open-in-view=true
spring.jpa.properties.hobernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=create

# Config para gerar o script de modelo de dados automaticamente, descomentar para executar uma vez.
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=src/main/resources/db/scripts/schema.sql

#logging.level.org.hibernate.type=trace

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=3
# 30s
spring.datasource.hikari.idle-timeout=30000

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration,classpath:db/testdata

spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-ignored-properties=true
